### ISSUE TITLE
Object reserved keyword

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-barcode#1]
The `object` keyword became reserved in PHP 7, this conflicts with the `Zend\Barcode\Object;`
namespace.

http://php.net/manual/en/reserved.other-reserved-words.php

---

Originally posted by @fntlnz at https://github.com/zendframework/zend-barcode/issues/14

**Comment by weierophinney** [comment]
@fntlnz It doesn't. The reason is because the namespace is not `Object`, but `Zend\Barcode\Object`; our tests even pass currently on PHP 7.

Do you have a specific example demonstrating breakage?


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-185409410

**Comment by weierophinney** [comment]
@weierophinney  The `object` keyword does not lead to an immediate breakage (like Int, Float and String) because is not marked as reserved in the current implementations of the PHP language (PHP, HHVM etc) but has been reserved for the future use as stated by these documentes:
- PHP Documentation [here](http://php.net/manual/en/reserved.other-reserved-words.php) 

> These words cannot be used to name a class, interface or a trait. These words are also prohibited from being used in namespaces. Some of the words are reserved to enable future PHP features without breaking backward compatibility. [...followed by a table containing reserved names including object]
- PHP language specification [here](https://github.com/php/php-langspec/blob/cfdcbd2025d2a225dd9ce9cd838dc515d60ebb47/spec/09-lexical-structure.md#names)

> The following names are reserved for future use and should not be used as the names of classes, interfaces, or traits: mixed, numeric, object, and resource.


---

Originally posted by @fntlnz at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-185605513

**Comment by weierophinney** [comment]
`Object` is used as _namespace_ not as class, interface or trait.


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-185618017

**Comment by weierophinney** [comment]
So, what's the point?

From: http://php.net/manual/en/reserved.other-reserved-words.php

> These words are also prohibited from being used in namespaces


---

Originally posted by @fntlnz at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-185621519

**Comment by weierophinney** [comment]
As @weierophinney point the namespace is the whole string. PHP does not distinguish namespace parts.

Probably `namespace Object {}` may fail due the restrictions you noticed but not `Foo\<any restricted word>`

Anyway if you found a better term for name the namespace we could consider start to use it in the next minor version (preserving the old namespace for BC)


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-185626165

**Comment by weierophinney** [comment]
Hello @fntlnz :) 

We can start to use a new name ( and mark this class as deprecated in order to remove it during 3.0 release
- Zend\Barcode\BarcodeObject
- Zend\Barcode\Barcode


---

Originally posted by @gianarb at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-185629586

**Comment by weierophinney** [comment]
Minimal fix in https://github.com/zendframework/zend-barcode/pull/36


---

Originally posted by @remicollet at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-338175760

**Comment by weierophinney** [comment]
Hi, we are also seeing this issue in PHP 7.2

PHP Fatal error:  Cannot use Zend\Barcode\Object as Object because 'Object' is a special class name in www/vhosts/api.content-manager/src/PhysicalLookbook/Service/PdfGenerator.php on line 26

Line 26:
use Zend\Barcode\Object;

Any help very welcome.

Thks



---

Originally posted by @dbarn at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-437343365

**Comment by weierophinney** [comment]
@dbarn 
Which version of zend-barcode do you use?

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-437343909

**Comment by weierophinney** [comment]
~~Fixed with #36 and released with version [2.6.1](https://github.com/zendframework/zend-barcode/releases/tag/release-2.6.1)~~

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-437344170

**Comment by weierophinney** [comment]
Related to #37 

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-437344349

**Comment by weierophinney** [comment]
Hi we are using 2.7
I have fixed by aliasing the object in our code:
Line 26:
use Zend\Barcode\Object as BarcodeObject

And then using 
$barcode = new Object\Ean13();

This work ok.



---

Originally posted by @dbarn at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-437347214

**Comment by weierophinney** [comment]
@dbarn 
Thanks for your feedback!

I will reopen this issue, because the problem with `Object` in namespace was not fixed and must be done on version 3.0!

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-barcode/issues/14#issuecomment-437348017

**Comment by simivar** [comment]
Wouldn't `Type` be a better namespace than `Object`?

**Comment by simivar** [comment]
What do you think about `Type` namespace instead of `Object`? Is it okay?

**Comment by weierophinney** [comment]
I worry that `Type` might be reserved at some point as well.

Honestly, these are all value objects _describing barcodes_. I'd name the namespace `Barcode`, the abstract class `AbstractBarcode`, and the `ObjectPluginManager` would become `BarcodePluginManager`.

**Comment by simivar** [comment]
I agree. What's the way you would like to do it? I was thinking about way so that we can mark current classes as `@dreprecated` and not double code. I came up with idea to add new classes in `Laminas\Barcode\Barcode` namespace that extend the old ones. The problem I see is that the new `Laminas\Barcode\Barcode\Codabar` will be child of `AbstractObject` from old namespace not of the new `AbstractBarcode`.

For example:
```php
// src/Barcode/Codabar.php
<?php
namespace Laminas\Barcode\Barcode;

use Laminas\Barcode\Object\Codabar as BaseCodabar;

class Codabar extends BaseCodabar
{
}
```

```php
// src/Object/Codabar.php
<?php
namespace Laminas\Barcode\Object;

/** 
 * @deprecated Deprecated in 2.8 and will be removed in 3.0. Use Laminas\Barcode\Barcode namespace instead.
 */
class Codabar extends AbstractObject
{
[...code...]
}
```

**Comment by weierophinney** [comment]
1. Create `AbstractBarcode` as an extension of `AbstractObject`.
2. Have each `Laminas\Barcode\Barcode\*` implementation extend `AbstractBarcode`, and move implementation details into those.
3. Have each `Laminas\Barcode\Object\*` class extend the variant in `Laminas\Barcode\Barcode\*`.

This ensures that each is a `Laminas\Barcode\Object\AbstractObject`, as well as a `Laminas\Barcode\Barcode\AbstractBarcode`, keeping BC with existing typehints, while allowing us to deprecate the old classes.

**Comment by tasmaniski** [comment]
I trigger this issue in version 2.6.0 when I migrate code from PHP 5.6 to 7.4. 
But I upgraded this package to 2.8.* version and there is no error. 
So this can be closed.
