### ISSUE TITLE
Can not install on Magento 2.4.1

### ISSUE THREAD

**Issue by mahesh-rajawat** [laminas/laminas-barcode#11]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.8.2

#### Summary

I am trying to install on Magento 2.4.1 via composer.

Below is the error coming on cli.
`Problem 1
    - Conclusion: don't install laminas/laminas-developer-tools 2.1.1
    - Conclusion: remove laminas/laminas-config 2.6.0
    - Installation request for laminas/laminas-developer-tools ^2.1 -> satisfiable by laminas/laminas-developer-tools[2.1.0, 2.1.1].
    - Conclusion: don't install laminas/laminas-config 2.6.0
    - laminas/laminas-developer-tools 2.1.0 requires laminas/laminas-modulemanager ^2.10 -> satisfiable by laminas/laminas-modulemanager[2.10.0, 2.10.1, 2.10.2].
    - laminas/laminas-modulemanager 2.10.0 requires laminas/laminas-config ^3.4 -> satisfiable by laminas/laminas-config[3.4.0, 3.5.0].
    - laminas/laminas-modulemanager 2.10.1 requires laminas/laminas-config ^3.4 -> satisfiable by laminas/laminas-config[3.4.0, 3.5.0].
    - laminas/laminas-modulemanager 2.10.2 requires laminas/laminas-config ^3.4 -> satisfiable by laminas/laminas-config[3.4.0, 3.5.0].
    - Can only install one of: laminas/laminas-config[3.4.0, 2.6.0].
    - Can only install one of: laminas/laminas-config[3.5.0, 2.6.0].
    - Installation request for laminas/laminas-config (locked at 2.6.0) -> satisfiable by laminas/laminas-config[2.6.0].`

#### How to reproduce
`composer require laminas/laminas-barcode:2.8`
****

#### Expected behavior

Must be installed successfully.

**Comment by Ocramius** [comment]
@mahesh-rajawat can you try a `composer why-not laminas/laminas-barcode:2.8`?

Also, can you try `composer why-not laminas/laminas-barcode:^2.8`?
