### ISSUE TITLE
Deprecated Functionality: imagepolygon(): Using the $num_points parameter is deprecated PHP 8.1

### ISSUE THREAD

**Issue by benhath** [laminas/laminas-barcode#17]
https://github.com/laminas/laminas-barcode/blob/0fae0391d77e7f4e23a3a2154046754e403f20cb/src/Renderer/Image.php#L490-L509

Fix is to remove $numPoints from line 501.

```php
        if (! $filled) {
            return imagepolygon($this->resource, $points, $color);
        }
`

**Comment by froschdesign** [comment]
@benhath 
Please create a pull request and make sure that version 7.4 is still supported.

https://github.com/laminas/laminas-barcode/blob/0fae0391d77e7f4e23a3a2154046754e403f20cb/composer.json#L22

Use the [2.11.x](https://github.com/laminas/laminas-barcode/tree/2.11.x) branch as target.
Thanks in advance! 👍

**Comment by ls-youssef-jlidat** [comment]
@froschdesign I have submitted a pull request to resolve this issue:
- https://github.com/laminas/laminas-barcode/pull/24
