### ISSUE TITLE
Composer installation error

### ISSUE THREAD

**Issue by erickneverson** [laminas/laminas-barcode#21]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.12.0

#### Summary

composer require laminas/laminas-barcode:2.12.0 results in installation of library and dependencies but also concludes with:

Failed to set PHP CodeSniffer installed_paths Config

#### Current behavior

Error during composer installation.  Usage of the library fails:
Undefined type 'Laminas\Barcode\Barcode'.

#### How to reproduce
with php 8.1 installed, run:
composer require laminas/laminas-barcode:2.12.0

#### Expected behavior

clean installation

**Comment by froschdesign** [comment]
@erickneverson 
I can not reproduce the problem, works as expected:

```bash
composer require laminas/laminas-barcode

./composer.json has been updated
Running composer update laminas/laminas-barcode
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking laminas/laminas-barcode (2.12.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading laminas/laminas-barcode (2.12.0)
  - Installing laminas/laminas-barcode (2.12.0): Extracting archive
Generating autoload files
43 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Using version ^2.12 for laminas/laminas-barcode
```

Can you provide the full output?

**Comment by weierophinney** [comment]
@froschdesign OP indicated a specific version when running the install command: `composer require laminas/laminas-barcode:2.12.0` - can you try that? (I'm not at my computer, so I can't try.)

@erickneverson what version of Composer?

**Comment by froschdesign** [comment]
@weierophinney 
Same result: no problem.

**Comment by Xerkus** [comment]
> Failed to set PHP CodeSniffer installed_paths Config

Problem can not be produced by this package. Issue is on the user side. 99% sure problem is with file ownership or permissions in vendor folder.

**Comment by erickneverson** [comment]
Hi,

Yea I think the problem is probably permissions related.  Nevertheless, here's my output

```
composer require laminas/laminas-barcode:2.12.0
./composer.json has been updated
Running composer update laminas/laminas-barcode
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 0 updates, 0 removals
  - Locking laminas/laminas-barcode (2.12.0)
  - Locking laminas/laminas-servicemanager (3.15.0)
  - Locking laminas/laminas-stdlib (3.17.x-dev a7c4067)
  - Locking laminas/laminas-validator (2.31.x-dev b904e5d)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing laminas/laminas-stdlib (3.17.x-dev a7c4067): Extracting archive
  - Installing laminas/laminas-servicemanager (3.15.0): Extracting archive
  - Installing laminas/laminas-validator (2.31.x-dev b904e5d): Extracting archive
  - Installing laminas/laminas-barcode (2.12.0): Extracting archive
7 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package zendframework/zendframework1 is abandoned, you should avoid using it. Use zendframework/zendframework instead.
Generating autoload files
48 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Failed to set PHP CodeSniffer installed_paths Config
```

**Comment by erickneverson** [comment]
> @froschdesign OP indicated a specific version when running the install command: `composer require laminas/laminas-barcode:2.12.0` - can you try that? (I'm not at my computer, so I can't try.)
> 
> @erickneverson what version of Composer?

composer:2.2.6
